baseURL = "http://nicholasmamo.github.io/NicholasMamo"
languageCode = "en-us"
title = "Blog | Nicholas Mamo"
theme = 'hugo-theme-mini'
canonifyUrls = true
googleAnalytics = "G-8L2KYY5HMZ"

[params]
enableGoogleAnalytics = true

[[params.Links]]
  name = 'About'
  path = '/pages/about'

[[params.Links]]
  name = 'Publications'
  path = '/pages/publications'
