baseURL = "http://nicholasmamo.github.io/NicholasMamo"
languageCode = "en-us"
title = "My New Hugo Site"
theme = 'hugo-theme-mini'
canonifyUrls = true
googleAnalytics = "G-8L2KYY5HMZ"

[params]
enableGoogleAnalytics = true
